#NEED TO IMPLEMENT KEY VAULT

#MYBATIS CONFIG
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.config-location=classpath:mybatis/config/sql-mapper-config.xml


#MYSQL CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/fastsns
spring.datasource.username=root
spring.datasource.password=123qwe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#REDIS CONFIG
spring.cache.type=redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.repositories.enabled=false

#SPRING SESSION
spring.session.store-type=redis


#VALUE PROPERTIES
JWT_SECRET=33dd323c5988af47a7979d15f41380d7be7fd1a01f65a8dd865ceeafb0fc8bcf
expire.defaultTime=60


